### ISSUE TITLE
'DualStreamProcessor' object has no attribute 'flush'

### ISSUE THREAD

**Issue by analyticmind** [ParisNeo/lollms-webui#315]
## Expected Behavior
I initially installed this earlier in the week, and I got answers in approximately 1 to 2 minutes. I am using CPU i7-8700T, with gpt4all groovy. Python version is 3.11.3. OS: Arch Linux. 

## Current Behavior
After reinstalling to get the latest, I'm getting the following error from the terminal, repeated over and over for several minutes until I kill the process:

```
AttributeError: 'DualStreamProcessor' object has no attribute 'flush' 
Exception ignored on calling ctypes callback function: <function GPT4ALL.generate.<locals>.local_callback at 0x7f68fa552020>
```

The result is that I'm not getting any answers from the model, although sometimes (rarely) it answers after 3 to 5 minutes, even with the error.

I'm not a programmer, so please let me know if more info is needed. Thanks!

**Comment by ParisNeo** [comment]
hi. Thanks for notifying me.
The problem is now fixed.
The guyes from Nomic AI use another context when it comes to streaming the tokens. That sucks because I can't even do a print with a flush in that context show my method that shows the number of tokens generated in the console results in errors.

Now I figured out a solution to that.
Pull last version

**Comment by analyticmind** [comment]
Thank you very much! The error has gone away now, and the answer came back in 45 seconds, as before.

**Comment by sabaimran** [comment]
Hey @ParisNeo , could you share a commit where you fixed this issue? I'm getting the same error in my application with GPT4All as a dependency.

**Comment by pseudotensor** [comment]
e07c76deb3be191a856f3643162b597e923b30f2
