### ISSUE TITLE
Access from remote computer with ip address

### ISSUE THREAD

**Issue by malocker** [ParisNeo/lollms-webui#345]
## Expected Behavior
access webui from another computer on the network with ip:9600

## Current Behavior
installation success work fine with local computer and url localhost:9600 but tried with ip address from local or remote computer get connection refused 

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. install webui on ubuntu 22.04 following instuction https://github.com/ParisNeo/lollms-webui
2. try to browse lollms with 4 diffrent browser
3. get error : connection refused

## Possible Solution
tryed to open firewall port 9600 tcp -- no success
put the ip instead of 0.0.0.0 on .env file host = ip -- no success
added manually the ip address on app.py instead of localhost -- no success

## Context
Please provide any additional context about the issue.

## Screenshots
screenshot from firefox dev tool
![lollms_connexion](https://github.com/ParisNeo/lollms-webui/assets/52939114/679ae3be-19d6-4e31-aedb-34782a4e8153)

**Comment by sam43b** [comment]
Hi,

run it with --listen cmdline param

 python app.py --listen 

Best,

**Comment by Aroy-Art** [comment]
Start the webui with 
```
bash webui.sh --host 0.0.0.0
```

**Comment by malocker** [comment]
@Aroy-Art  thanks a lot run with --host 0.0.0.0 make it available on the network with the IP address

**Comment by malocker** [comment]
@Aroy-Art  thanks a lot run with --host 0.0.0.0 make it available on the network with the IP address

**Comment by ParisNeo** [comment]
Yes, and you can make it accessible outside if you configure your rooter to forward the 9600 port to your pc address.

Just be aware that I don't have much money to buy a certificate and that's why the service is not crypted which means that someone can do a simple man in the middle attack and view what you are discussing with the AI.

You can use a private virtual network to cypher every thing between your device and your PC. I just want to be clear about this.
