### ISSUE TITLE
lollms & stable diffusion automatic 1111

### ISSUE THREAD

**Issue by sam43b** [ParisNeo/lollms-webui#347]
Hi,

How to use lollms with existing stable diffusion automatic 1111 ?? without reinstalling SD and downloading models ... etc

Best,

**Comment by ParisNeo** [comment]
Emm, technically, you should be able to run automatic 1111 with --api option which forces lollms to use it instead of its own version. But you still need at least to install the personality which will install the source code and a single model.

There is a mandatory file called lollms_sd.py that does not exist in the raw automatic 1111's code. you can keep that file and remove the rest.

The other solution is copy all your models to the lollms auto 1111's sdwebui, remove your other sd webui and use this one instead, it is always uptodate and can be started by artbot and even directly called from there:
![image](https://github.com/ParisNeo/lollms-webui/assets/827993/c31d29b2-8306-4407-91ae-86159628c344)
